##
# Example: 
# $ ansible-playbook -i inventory ocp42-backup-etcd.yml
# $ ansible-playbook -i inventory ocp42-backup-etcd.yml --extra-vars="backup_dst_path=/tmp/openshift42_backup"
##

- hosts: masters
  gather_facts: false
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  tasks:

    - name: Perform ETCD Backup
      import_role: 
        name: ocp_etcd_backup
      vars:
        backup_dst_path: "/tmp/ocp42-crc"
      run_once: true