##
# Example: 
# $ ansible-playbook -i inventory ocp42-restore-etcd.yml
# $ ansible-playbook -i inventory ocp42-restore-etcd.yml --extra-vars="backup_src_file=/backups/etcd/20200109092851-snapshot.db"
##

- hosts: masters
  gather_facts: false
  tasks:

    - name: Perform ETCD Backup
      import_role: 
        name: ocp_etcd_restore
      vars:
        backup_src_file: "/tmp/ocp42-crc/latest-snapshot.db"


