##
# Example: 
# $ ansible-playbook -i inventory ocp42-restore-etcd.yml
# $ ansible-playbook -i inventory ocp42-restore-etcd.yml --extra-vars="backup_src_file=/backups/etcd/20200109092851-snapshot.db"
##

- hosts: all
  vars:
    backup_src_file:  "/tmp/ocp42-crc/latest-snapshot.db"
    backup_dst_file:  "/tmp/snapshot.db"

  tasks:

    - debug:
        msg: "Source Machine (Bastion) -> Backup File: {{ backup_src_file }}"
        verbosity: 1

    - debug:
        msg: "Destination Machine (Master) -> Backup File: {{ backup_dst_file }}"
        verbosity: 1
  
    - name: Copy ETCD backup file
      copy:
        src: "{{ backup_src_file }}"
        dest: "{{ backup_dst_file }}"
        force: yes

    - name: Obtain ETCD member
      shell: id=$(sudo crictl ps --name etcd-member | awk 'FNR==2{ print $1}') && sudo crictl exec -it $id etcdctl --cacert="/etc/ssl/etcd/ca.crt" --cert="/etc/ssl/etcd/system:etcd-peer:etcd-0.crc.testing.crt" --key="/etc/ssl/etcd/system:etcd-peer:etcd-0.crc.testing.key" member list -w json
      become: true
      register: etcd_members_json

    - debug:
        var: etcd_members_json.stdout
        verbosity: 1

    - name: Test with a message
      etcd_members_parser:
        json: "{{ etcd_members_json.stdout }}"
      register: etcd_members_parsed

    - debug:
        var: etcd_members_parsed
        verbosity: 1

    - name: Restore ETCD backup
      # shell: "/usr/local/bin/etcd-snapshot-restore.sh {{ backup_dst_file }} $INITIAL_CLUSTER"
      shell: "echo $INITIAL_CLUSTER"
      become: true
      environment:
        INITIAL_CLUSTER: "{{ etcd_members_parsed.message }}"
