##
# Example: 
# $ ansible-playbook -i inventory ocp42-restore-etcd.yml
# $ ansible-playbook -i inventory ocp42-restore-etcd.yml --extra-vars="backup_src_file=/tmp/latest-snapshot.db"
##

- hosts: masters
  gather_facts: false
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  tasks:

    - name: Perform ETCD Backup
      import_role: 
        name: ocp_etcd_restore
      vars:
        backup_src_file: "/tmp/latest-snapshot.db"


